# docker-compose.dev.yaml - Solo para desarrollo local
services:
  backend:
    image: djohann28/automated-exam-generation.backend:1.0
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    image: djohann28/automated-exam-generation.frontend:1.0
    ports:
      - "4200:4200"
    depends_on:
      - backend